#!/usr/bin/env bash
# From https://github.com/holman/dotfiles/blob/master/script/install
# (with slight modifications)
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
