#!/usr/bin/env bash
# From https://github.com/holman/dotfiles/blob/master/script/install
# (with slight modifications)
#
# Run all dotfiles installers.

set -e

source "$(dirname $0)/lib/info_printer.bash"

dot_dir=`dirname $0`/..

text_info script/install "› cd ${dot_dir}"
cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.bash | while read installer; do
  text_info script/install "› sh -c \"${installer}\""
  sh -c "${installer}"
done
